name: stand_mapping

channels:
  - conda-forge
  - pytorch

dependencies:
  - descartes
  - geopandas
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python
  - python-dotenv
  - pytorch
  - rasterio
  - scikit-image
  - scikit-learn
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - torchvision

prefix: /home/ddiaz/anaconda3/stand_mapping
